// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifxryybuqwohfgcrryer.supabase.co"
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmeHJ5eWJ1cXdvaGZnY3JyeWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1NDcwODMsImV4cCI6MjA3NjEyMzA4M30.opAiQUuYpBI_rr6xtbFC94hjVu4PJ8HNBDcRRXFyqyk"

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});